### ISSUE TITLE
Force the bbox to stay in the image?

### ISSUE THREAD

**Issue by baristahell** [VolkerH/np_obb#8]
Hey! Thanks for your work, I'm already putting it to good use ;)
I have a problem thought. Some of my applications don't work too well if my polygons have coordinates outside the image (so not in the range [0,img_size]). 
And this happens everytime I have polygons that are close to the image borders.
For example :
```
polygon = [[0, 0], [0, 10], [10, 10]]
corners, center = nobb.get_obb_from_points(polygon)
```
returns : 
`corners[0:4] = [[[10.0, 9.999999999999998],
                          [4.999999999999998, 15.0],
                          [-5.0, 4.999999999999998],
                          [2.5121479338940403e-15, -2.5121479338940395e-15]]]`

For example this is a bbox for a polygon that's just slightly cut by the image. The original polygon has no point outside the image.
![sp_label_example](https://user-images.githubusercontent.com/24407720/76073971-cb61ad80-5f9a-11ea-861f-ef3234d9b9d2.png)

I was wondering if there was a way to force the bboxes to be the "best bbox inside the image" rather than the "best bbox overall"

Thanks !

**Comment by VolkerH** [comment]
Thanks for the feedback.

I'll have to think about that for a bit. Looking at this for a couple of minutes just now I am not sure how to approach the issue (or whether I have 100% understood the issue, can you maybe draw what you were hoping for as a bounding box instead of the blue rectangle ?).
 
I wont be able to devote much time to this in the coming two weeks but after that
I actually had some plans to change the fit method used here (which is not guaranteed to give the optimal result) to one that is based on the rotating calipers algorithm (which is guaranteed to give the minimum area bounding box) in the coming weeks. Maybe I can add the inside the image as a constraint somehow.

**Comment by VolkerH** [comment]
Hi @baristahell,

Looking at your above example I really don't quite see what the best oriented bounding box inside the image would look like, in particular if I want to include everything that is visible. My handdrawn sketch looks like this:

![image](https://user-images.githubusercontent.com/2210044/76173042-c6496c00-61ef-11ea-88af-106bc2c281cd.png)

which is basically the same as a non-oriented bounding box.
This is because you need to include the edge that is the intersection with the original polygon (which I assume were the outlines of the building) with the image boundary. This gives you an edge segment that is aligned with the image frame.

However, I may have misunderstood what you want. A small sketch would be helpful.

**Comment by baristahell** [comment]
Hello! Thanks for your answer. What I mean is the following : 
![bes_obb_illu](https://user-images.githubusercontent.com/24407720/76205200-0c0b3200-61fa-11ea-98ae-94ab3fc3910d.jpg)
- Green: the original polygon
- Blue: the OBB np_obb generates
-  Yellow: the "best fit inside the image" OBB

So yes sometimes it might be the same as a regular bbox but the idea would be to maximize the overlap between the original polygon and the generated OBB such as all coordinates of the OBB stay contained in the range [min(original_polygon), max(originalpolygon)] on x and y. It wouldn't include everything that's visible in the cases one point (it already can't be several points) of the bbox would fall outside the image.
On my example I think the bottom one would be more tilted and wouldn't exactly follow the original polygon's contours if the OBB would be optimal for overlap so maybe it's not a good illustration.

I know it may not be a realistic idea for a constraint as it might be very tricky but it was mainly to know if you'd already thought about this kind of issue. If you haven't planned on something like that and don't to waste too much time on a feature I'm the only one interested in, i wouldn't be mad ^^'

**Comment by baristahell** [comment]
Yeah maybe the second case would lead to something like that 
![best_obb_2](https://user-images.githubusercontent.com/24407720/76205691-0a8e3980-61fb-11ea-80a7-68263b6fd2d8.jpg)
Like I said I don't know if it's realistic or a useful feature, maybe I should think of something on my end but if you have any idea on how to do that I'm listening 
Thanks a lot for your time nonetheless!

**Comment by VolkerH** [comment]
Thanks for the clarification. I perfectly see what you want there, but those boxes are no longer bounding the visible part of the object. 

The best way I can think of is to look for the intersections between the original bounding box sides and the image boundaries. From these intersections, create an orthogonal line to intersect the boundding box. As there are several intersections possible, test all of them and check which of the cut bboxes that are entirely in the image has the largest area.

But I think you will have to find your own solution for that. I cannot justify spending time on this as it does not align with my work at the moment.

**Comment by baristahell** [comment]
Yeah of course. It was just something I thought would be useful for me and if you don't have the time of don't want to do it it's obviously fair.
Thanks for your answers thought, I'm already working on a similar idea for splitting the polygons into rectangles so I'll see how it goes! Thanks
